"""empty message

Revision ID: 2451e670f9d0
Revises: 73e3dd2f4819
Create Date: 2021-08-12 11:33:09.567187

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2451e670f9d0'
down_revision = '73e3dd2f4819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=30), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('activity_level', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id'),
    mysql_collate='utf8_general_ci'
    )
    op.create_table('Diet',
    sa.Column('diet_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meal', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('food_info', sa.JSON(), nullable=True),
    sa.Column('cal', sa.Integer(), nullable=True),
    sa.Column('img_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('diet_id'),
    sa.UniqueConstraint('diet_id'),
    mysql_collate='utf8_general_ci'
    )
    op.create_table('Recommended',
    sa.Column('rec_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cal', sa.Integer(), nullable=True),
    sa.Column('carbs', sa.Float(), nullable=True),
    sa.Column('fat', sa.Float(), nullable=True),
    sa.Column('protein', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('rec_id'),
    sa.UniqueConstraint('rec_id'),
    sa.UniqueConstraint('user_id'),
    mysql_collate='utf8_general_ci'
    )
    op.drop_index('user_id', table_name='user')
    op.drop_table('user')
    op.drop_index('rec_id', table_name='recommended')
    op.drop_index('user_id', table_name='recommended')
    op.drop_table('recommended')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommended',
    sa.Column('rec_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cal', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('carbs', mysql.FLOAT(), nullable=True),
    sa.Column('fat', mysql.FLOAT(), nullable=True),
    sa.Column('protein', mysql.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='recommended_ibfk_1'),
    sa.PrimaryKeyConstraint('rec_id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id', 'recommended', ['user_id'], unique=False)
    op.create_index('rec_id', 'recommended', ['rec_id'], unique=False)
    op.create_table('user',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_name', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('height', mysql.FLOAT(), nullable=True),
    sa.Column('weight', mysql.FLOAT(), nullable=True),
    sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gender', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('activity_level', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email', mysql.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_index('user_id', 'user', ['user_id'], unique=False)
    op.drop_table('Recommended')
    op.drop_table('Diet')
    op.drop_table('User')
    # ### end Alembic commands ###
