"""empty message

Revision ID: 3c7ef9b933e7
Revises: 7d1c2cbdeb4c
Create Date: 2021-08-12 11:39:05.563313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c7ef9b933e7'
down_revision = '7d1c2cbdeb4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=30), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('activity_level', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id'),
    mysql_collate='utf8_general_ci'
    )
    op.create_table('Diet',
    sa.Column('diet_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meal', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('food_info', sa.JSON(), nullable=True),
    sa.Column('cal', sa.Integer(), nullable=True),
    sa.Column('img_path', sa.String(length=320), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('diet_id'),
    sa.UniqueConstraint('diet_id'),
    mysql_collate='utf8_general_ci'
    )
    op.create_table('Recommended',
    sa.Column('rec_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cal', sa.Integer(), nullable=True),
    sa.Column('carbs', sa.Float(), nullable=True),
    sa.Column('fat', sa.Float(), nullable=True),
    sa.Column('protein', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('rec_id'),
    sa.UniqueConstraint('rec_id'),
    sa.UniqueConstraint('user_id'),
    mysql_collate='utf8_general_ci'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Recommended')
    op.drop_table('Diet')
    op.drop_table('User')
    # ### end Alembic commands ###
